# Traefik configuration for Nextcloud AIO with secure headers and HTTPS redirection
http:
  routers:
    nextcloud:
      entrypoints:
        - "https"
      rule: "Host(`nc.datia.me`)"
      middlewares:
        - https-redirect
        - nextcloud-secure-headers
      tls:
        domains:
          - main: "nc.datia.me"
      service: nextcloud
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000"
        passHostHeader: true
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customResponseHeaders:
          X-Robots-Tag: "none"