networks:
  proxy:
    external: true

services:
    wg-easy:
      image: ghcr.io/wg-easy/wg-easy:14 # TODO: migrate version to ghcr.io/wg-easy/wg-easy:15
      container_name: wg-easy
      environment:
        WG_HOST: '${DOMAIN}'
        PASSWORD_HASH: '${WIREGUARD_PW}'
      volumes:
        - ${WORKDIR}/etc:/etc/wireguard
      ports:
        - "51820:51820/udp"
        # - "51821:51821/tcp" # Uncomment if you want to use the web interface
      restart: unless-stopped
      networks:
        - proxy
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
      labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wireguard.entrypoints=web"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.${DOMAIN}`)"
      - "traefik.http.middlewares.wireguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wireguard.middlewares=wireguard-https-redirect"
      - "traefik.http.routers.wireguard-secure.entrypoints=websecure"
      - "traefik.http.routers.wireguard-secure.rule=Host(`wireguard.${DOMAIN}`)"
      - "traefik.http.routers.wireguard-secure.tls=true"
      - "traefik.http.routers.wireguard-secure.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"