---
- Networking:
    - FritzBox:
        href: http://192.168.178.1
        icon: fritzbox.svg
        description: Router
        siteMonitor: http://192.168.178.1
        widget:
            type: fritzbox
            url: http://192.168.178.1
    - PiHole:
        href: http://pihole.local/admin # https://pihole.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: pi-hole.svg
        description: DNS - rpi-nico-small
        container: pihole
        widget:
            type: pihole
            url: http://pihole.local # https://pihole.{{ HOMEPAGE_VAR_DOMAIN }}
            version: 6
            key: '{{HOMEPAGE_VAR_PIHOLE_KEY}}'
    # - Wireguard:
    #     href: https://wireguard.{{ HOMEPAGE_VAR_DOMAIN }}
    #     icon: wireguard.png
    #     description: wireguard-prod-1 on rpi-angel-1
    #     container: wg-easy
    - Traefik:
        href: https://traefik-dashboard.{{ HOMEPAGE_VAR_DOMAIN }}/
        icon: traefik.svg
        description: Traefik - rpi-angel-1
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080

- Storage:
    - QNAP 462:
        href: http://192.168.178.48:8080/cgi-bin/ # TODO
        icon: qnap.svg
        description: qnap-462 NAS
    - NextCloud:
        href: "https://nextcloud.{{ HOMEPAGE_VAR_DOMAIN }}"
        icon: nextcloud.svg
        description: Drive app - rpi-angel-1
        container: nextcloud
    - Immich:
        href: "https://immich.{{ HOMEPAGE_VAR_DOMAIN }}"
        icon: immich.svg
        description: Photo app - rpi-angel-1
        container: immich_server


- Management:
    - Portainer:
        href: https://portainer.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: portainer.svg
        description: Container management - rpi-angel-1
        container: portainer
    - Watchtower:
        # href: https://watchtower.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: watchtower.svg
        description: Container auto update - rpi-angel-1
        container: watchtower
        # widget:
        #     type: watchtower
        #     url: http://watchtower:8080
        #     key: {{HOMEPAGE_VAR_WATCHTOWER_KEY}}

- Monitoring:
    - Grafana:
        href: https://grafana.${HOMEPAGE_VAR_DOMAIN}
        description: Graphs used for device stats - rpi-angel-1
        icon: grafana.svg
        container: grafana
        # widget:
        #     type: grafana
        #     url: https://grafana.{{ HOMEPAGE_VAR_DOMAIN }}
        #     username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
        #     password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - Uptime Kuma:
        href: https://uptime-kuma.{{ HOMEPAGE_VAR_DOMAIN }}
        description: Monitoring of apps - rpi-angel-1
        icon: uptime-kuma.svg
        container: uptime-kuma
        # widget:
        #     type: uptimekuma
        #     url: https://uptime-kuma.{{ HOMEPAGE_VAR_DOMAIN }}
        #     key: {{HOMEPAGE_VAR_UPTIMEKUMA_KEY}}
    - Prometheus:
        href: https://prometheus.{{ HOMEPAGE_VAR_DOMAIN }}
        description: Metric collector - rpi-angel-1
        icon: prometheus.svg
        container: prometheus

- AI:
    - ChatGPT:
        href: https://chatgpt.com
        icon: chatgpt.svg
    - Ollama:
        href: http://ollama:11434
        icon: si-ollama-#FFFFFF
        description: AI model server - rpi-angel-1
        container: ollama
    - OpenWebUI:
        href: http://openwebui:3003
        icon: chatgpt.svg
        description: Web UI for AI - rpi-angel-1
        container: openwebui

- Automation:
    - Home Assistant:
        href: https://homeassistant.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: home-assistant.svg
        description: Automation server - rpi-angel-1
        container: homeassistant

- Media:
    - Plex:
        href: https://plex.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: plex.svg
        description: Media server - rpi-angel-1
        container: plex
    - Jellyfin:
        href: https://jellyfin.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: jellyfin.svg
        description: Open source media server - rpi-angel-1
        container: jellyfin
    - AudioBookShelf:
        href: https://audiobookshelf.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: audiobookshelf.svg
        description: Audiobook server - rpi-angel-1
        container: audiobookshelf

- Torrent:
    - Prowlarr:
        href: https://prowlarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: prowlarr.svg
        description: Indexer manager for all your apps - rpi-angel-1
        container: prowlarr
    - Jackett:
        href: https://jackett.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: jackett.svg
        description: Indexer manager for all your apps - rpi-angel-1
        container: jackett
    - Overseerr:
        href: https://overseerr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: overseerr.svg
        description: Media request management tool for Plex and Jellyfin - rpi-angel-1
        container: overseerr
        # widget:
        #     type: overseerr
        #     url: https://overseerr.{{ HOMEPAGE_VAR_DOMAIN }}
        #     key: {{HOMEPAGE_VAR_OVERSEERR_KEY}}
    - Sonarr:
        href: https://sonarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: sonarr.svg
        description: Automates the downloading of TV shows - rpi-angel-1
        container: sonarr
    - Radarr:
        href: https://radarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: radarr.svg
        description: Automates the downloading of movies - rpi-angel-1
        container: radarr
    - Bazarr:
        href: https://bazarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: bazarr.svg
        description: Automates the downloading of subtitles - rpi-angel-1
        container: bazarr
    - Lidarr:
        href: https://lidarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: lidarr.svg
        description: Automates the downloading of music - rpi-angel-1
        container: lidarr
    - Readarr:
        href: https://readarr.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: readarr.svg
        description: Automates the downloading of books - rpi-angel-1
        container: readarr
    - Bittorrent:
        href: https://bittorrent.{{ HOMEPAGE_VAR_DOMAIN }}
        icon: si-bittorrent
        description: Torrent client - rpi-angel-1
        container: bittorrent
