---
- Networking:
    - FritzBox:
        href: http://192.168.178.1
        icon: fritzbox.svg
        description: Router
        siteMonitor: http://192.168.178.1
        widget:
            type: fritzbox
            url: http://192.168.178.1
    - PiHole:
        href: http://192.168.178.10/admin
        icon: pi-hole.svg
        description: DNS - rpi-nico-small
        ping: http://192.168.178.10/admin
        widget:
            type: pihole
            url: http://192.168.178.10
            version: 6
            key: '{{HOMEPAGE_VAR_PIHOLE_KEY}}'
    # - Wireguard:
    #     href: https://wireguard.docker.sheetgenius.app
    #     icon: wireguard.png
    #     description: wireguard-prod-1 on docker
    #     container: wg-easy
    - Traefik:
        href: https://traefik-dashboard.docker.sheetgenius.app/
        icon: traefik.svg
        description: Reverse Proxy - docker
        container: traefik

- Storage:
    - QNAP 462:
        href: http://192.168.178.5:8080/cgi-bin/ # TODO
        icon: qnap.svg
        description: qnap-462 NAS
        ping: http://192.168.178.5:8080/cgi-bin/ # TODO
    - NextCloud:
        href: "https://nextcloud.docker.sheetgenius.app"
        icon: nextcloud.svg
        description: Drive app - docker
        container: nextcloud
    - Immich:
        href: "https://immich.docker.sheetgenius.app"
        icon: immich.svg
        description: Photo app - docker
        container: immich_server
    - Paperless-ngx:
        href: "https://paperless.docker.sheetgenius.app"
        icon: paperless-ngx.svg
        description: Document management - docker
        container: paperless-ngx-paperless-webserver-1

- Management:
    - Portainer:
        href: https://portainer.docker.sheetgenius.app
        icon: portainer.svg
        description: Container management - docker
        container: portainer
    - Watchtower:
        icon: watchtower.svg
        description: Container auto update - docker
        container: watchtower
    # - Home Assistant:
    #     href: https://homeassistant.docker.sheetgenius.app
    #     icon: home-assistant.svg
    #     description: Automation server - docker
    #     container: homeassistant


- Monitoring:
    - Grafana:
        href: https://grafana.docker.sheetgenius.app
        description: Graphs used for device stats - docker
        icon: grafana.svg
        container: grafana
    - Uptime Kuma:
        href: https://uptime-kuma.docker.sheetgenius.app
        description: Monitoring of apps - docker
        icon: uptime-kuma.svg
        container: uptime-kuma
    - Prometheus:
        href: https://prometheus.docker.sheetgenius.app
        description: Metric collector - docker
        icon: prometheus.svg
        container: prometheus

# - AI:
#     - ChatGPT:
#         href: https://chatgpt.com
#         icon: chatgpt.svg
#     - Ollama:
#         href: http://ollama:11434
#         icon: si-ollama-#FFFFFF
#         description: AI model server - docker
#         container: ollama
#     - OpenWebUI:
#         href: http://openwebui:3003
#         icon: chatgpt.svg
#         description: Web UI for AI - docker
#         container: openwebui

- Media:
    # - Plex:
    #     href: https://plex.docker.sheetgenius.app
    #     icon: plex.svg
    #     description: Media server - docker
    #     container: plex
    - Jellyfin:
        href: https://jellyfin.docker.sheetgenius.app
        icon: jellyfin.svg
        description: Open source media server - docker
        container: jellyfin
    # - AudioBookShelf:
    #     href: https://audiobookshelf.docker.sheetgenius.app
    #     icon: audiobookshelf.svg
    #     description: Audiobook server - docker
    #     container: audiobookshelf

- Torrent:
    - Jellyseerr (Jellyfin):
        href: https://jellyseerr-jellyfin.docker.sheetgenius.app
        icon: jellyseerr.svg
        description: Movie and TV show request management - docker
        container: jellyseerr-jellyfin
    - Gluetun:
        icon: gluetun.svg
        description: VPN client - docker
        container: gluetun
    - Qbittorrent:
        href: https://qbittorrent.docker.sheetgenius.app
        icon: si-qbittorrent
        description: Torrent client - docker
        container: qbittorrent
    - Prowlarr:
        href: https://prowlarr.docker.sheetgenius.app
        icon: prowlarr.svg
        description: Indexer manager for all your apps - docker
        container: prowlarr
    - Sonarr:
        href: https://sonarr.docker.sheetgenius.app
        icon: sonarr.svg
        description: Automates the downloading of TV shows - docker
        container: sonarr
    - Radarr:
        href: https://radarr.docker.sheetgenius.app
        icon: radarr.svg
        description: Automates the downloading of movies - docker
        container: radarr
    - Bazarr:
        href: https://bazarr.docker.sheetgenius.app
        icon: bazarr.svg
        description: Automates the downloading of subtitles - docker
        container: bazarr
    # - Readarr:
    #     href: https://readarr.docker.sheetgenius.app
    #     icon: readarr.svg
    #     description: Automates the downloading of books - docker
    #     container: readarr
    # - Lidarr:
    #     href: https://lidarr.docker.sheetgenius.app
    #     icon: lidarr.svg
    #     description: Automates the downloading of music - docker
    #     container: lidarr
