- Networking:
    - FritzBox:
        href: http://192.168.178.1
        icon: fritzbox.svg
        description: Router
        siteMonitor: http://192.168.178.1
        widget:
            type: fritzbox
            url: http://192.168.178.1
    - PiHole:
        href: http://192.168.178.10/admin
        icon: pi-hole.svg
        description: DNS - rpi-nico-small
        ping: http://192.168.178.10/admin
    - Traefik:
        href: https://traefik-dashboard.docker.datia.me/
        icon: traefik.svg
        description: Reverse Proxy - docker
        container: traefik

- Storage:
    - QNAP 462:
        href: http://192.168.178.5:8080/cgi-bin/
        icon: qnap.svg
        description: qnap-462 NAS
        ping: http://192.168.178.5:8080/cgi-bin/
    - NextCloud:
        href: "https://nextcloud.docker.datia.me"
        icon: nextcloud.svg
        description: Drive app - docker
        container: nextcloud
    - Immich:
        href: "https://immich.docker.datia.me"
        icon: immich.svg
        description: Photo app - docker
        container: immich_server
    - Paperless-ngx:
        href: "https://paperless.docker.datia.me"
        icon: paperless-ngx.svg
        description: Document management - docker
        container: paperless-ngx-paperless-webserver-1

- Management:
    - Portainer:
        href: https://portainer.docker.datia.me
        icon: portainer.svg
        description: Container management - docker
        container: portainer
    - Watchtower:
        icon: watchtower.svg
        description: Container auto update - docker
        container: watchtower

- Monitoring:
    - Grafana:
        href: https://grafana.docker.datia.me
        description: Graphs used for device stats - docker
        icon: grafana.svg
        container: grafana
    - Uptime Kuma:
        href: https://uptime-kuma.docker.datia.me
        description: Monitoring of apps - docker
        icon: uptime-kuma.svg
        container: uptime-kuma
    - Prometheus:
        href: https://prometheus.docker.datia.me
        description: Metric collector - docker
        icon: prometheus.svg
        container: prometheus

- Media:
    - Jellyfin:
        href: https://jellyfin.docker.datia.me
        icon: jellyfin.svg
        description: Open source media server - docker
        container: jellyfin
    - Jellyseerr (Jellyfin):
        href: https://jellyseerr-jellyfin.docker.datia.me
        icon: jellyseerr.svg
        description: Movie and TV show request management - docker
        container: jellyseerr-jellyfin

- Download & Infrastructure:
    - Qbittorrent:
        href: https://qbittorrent.docker.datia.me
        icon: si-qbittorrent
        description: Torrent client - docker
        container: qbittorrent
    - Gluetun:
        icon: gluetun.svg
        description: VPN client - docker
        container: gluetun
    - Gluetun-Anime:
        icon: gluetun.svg
        description: VPN client for anime - docker
        container: gluetun-anime
    - Gluetun-4K:
        icon: gluetun.svg
        description: VPN client for 4K media - docker
        container: gluetun-4k

- Content Management:
    - Prowlarr:
        href: https://prowlarr.docker.datia.me
        icon: prowlarr.svg
        description: Indexer manager for all your apps - docker
        container: prowlarr
    - Radarr:
        href: https://radarr.docker.datia.me
        icon: radarr.svg
        description: Automates the downloading of movies - docker
        container: radarr
    - Radarr-Anime:
        href: https://radarr-anime.docker.datia.me
        icon: radarr.svg
        description: Automates the downloading of anime movies - docker
        container: radarr-anime
    - Radarr-4K:
        href: https://radarr-4k.docker.datia.me
        icon: radarr.svg
        description: Automates the downloading of 4K movies - docker
        container: radarr-4k
    - Sonarr:
        href: https://sonarr.docker.datia.me
        icon: sonarr.svg
        description: Automates the downloading of TV shows - docker
        container: sonarr
    - Sonarr-Anime:
        href: https://sonarr-anime.docker.datia.me
        icon: sonarr.svg
        description: Automates the downloading of anime TV shows - docker
        container: sonarr-anime
    - Sonarr-4K:
        href: https://sonarr-4k.docker.datia.me
        icon: sonarr.svg
        description: Automates the downloading of 4K TV shows - docker
        container: sonarr-4k
    - Bazarr:
        href: https://bazarr.docker.datia.me
        icon: bazarr.svg
        description: Automates the downloading of subtitles - docker
        container: bazarr
