networks:
  proxy:
    external: true

services:
# --- Uptime Kuma Image
  uptime-kuma:
    image: louislam/uptime-kuma:2.1.1
    container_name: uptime-kuma
    volumes:
      - ${WORKDIR}/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
      # # Web Interface (using traefik)
      # - "8160:3001"
    restart: unless-stopped
    labels:
      # Traefik labels
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.uptime-kuma.entrypoints=http
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN}`)
      - traefik.http.middlewares.uptime-kuma-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.uptime-kuma.middlewares=uptime-kuma-https-redirect
      - traefik.http.routers.uptime-kuma-secure.entrypoints=https
      - traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.${DOMAIN}`)
      - traefik.http.routers.uptime-kuma-secure.tls=true
      - traefik.http.routers.uptime-kuma-secure.tls.certresolver=cloudflare
      - traefik.http.routers.uptime-kuma-secure.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      # Watchtower labels
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy
