name: Lint Compose Files

on:
  pull_request:

jobs:
  compose-lint:
    runs-on: ubuntu-latest
    container:
      image: docker:28.5-cli
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Validate Compose files
        run: |
          set -euo pipefail
          for file in $(find docker-apps -name docker-compose.yaml); do
            echo "################"
            echo "Validating $file"
            echo "################"
            docker compose -f "$file" config > /dev/null
          done
